name: Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update and Restart
        run: |
          # 1. Go to the PROD folder (not the temp runner folder)
          cd /home/mac/portfolio

          # 2. Pull latest code
          git pull origin main

          # 3. Build (Using full path to ensure it finds pnpm)
          # If pnpm isn't found, we can fix the path later.
          pnpm install --frozen-lockfile
          pnpm build

          # 4. Restart
          pm2 restart portfolio
